### ISSUE TITLE
The scanlines scroll downward slowly

### ISSUE THREAD

**Issue by sandord** [mattiasgustavsson/steem-crt#1]
First of all, this is a very awesome shader!

There's just this little thing I noticed: The scanlines scroll downward slowly. It's kind of subtle but I wonder if this is just my machine.

**Comment by mattiasgustavsson** [comment]
Thank you :)

The scrolling scanlines is very much intentional - it gives a bit more liveliness to the whole effect, I find. Not so accurate maybe, but then not much about this shader is - it is more meant to be a stylized thing :P

**Comment by sandord** [comment]
Alright, I get that :)

I read you might release a configurable version in the future (no pressure there). Perhaps you could include a flag for the scrolling lines when it comes to that?

Thanks!
